name: Deploy static HTML to GitHub Pages

on:
  # Workflow uruchamia się przy pushu na gałąź "main"
  push:
    branches: ["main"]

  # Workflow można uruchomić ręcznie przez kartę "Actions"
  workflow_dispatch:

# Ustawienia uprawnień dla GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Pozwala tylko na jeden równoczesny proces wdrożenia
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job dla budowania
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload static HTML to _site folder
        run: |
          mkdir -p _site
          cp -r * _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Job dla wdrożenia na GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
